"""Add remaining tables

Revision ID: 24040cd554a6
Revises: 9894e6dc63e2
Create Date: 2026-07-17 17:50:22.316168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


from app.models.post import SQLiteCompatibleArray


# revision identifiers, used by Alembic.
revision: str = '24040cd554a6'
down_revision: Union[str, Sequence[str], None] = '9894e6dc63e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_posts',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('platforms', SQLiteCompatibleArray(sa.String(length=50)), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='draft', nullable=False),
    sa.Column('scheduled_publish_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_publish_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_social_posts_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_posts'))
    )
    op.create_index(op.f('ix_social_posts_status'), 'social_posts', ['status'], unique=False)
    op.create_index(op.f('ix_social_posts_user_id'), 'social_posts', ['user_id'], unique=False)
    op.create_table('analytics_metrics',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=True),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('metric_value', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['social_posts.id'], name=op.f('fk_analytics_metrics_post_id_social_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_metrics'))
    )
    op.create_index(op.f('ix_analytics_metrics_metric_type'), 'analytics_metrics', ['metric_type'], unique=False)
    op.create_index(op.f('ix_analytics_metrics_platform'), 'analytics_metrics', ['platform'], unique=False)
    op.create_index(op.f('ix_analytics_metrics_post_id'), 'analytics_metrics', ['post_id'], unique=False)
    op.create_index(op.f('ix_analytics_metrics_timestamp'), 'analytics_metrics', ['timestamp'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_approval_requests_approved_by_users')),
    sa.ForeignKeyConstraint(['post_id'], ['social_posts.id'], name=op.f('fk_approval_requests_post_id_social_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_approval_requests_requested_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_requests'))
    )
    op.create_index(op.f('ix_approval_requests_post_id'), 'approval_requests', ['post_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_status'), 'approval_requests', ['status'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='new', nullable=False),
    sa.Column('source_platform', sa.String(length=50), nullable=True),
    sa.Column('source_post_id', sa.Uuid(), nullable=True),
    sa.Column('utm_source', sa.String(length=100), nullable=True),
    sa.Column('utm_medium', sa.String(length=100), nullable=True),
    sa.Column('utm_campaign', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['source_post_id'], ['social_posts.id'], name=op.f('fk_leads_source_post_id_social_posts'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads'))
    )
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=True)
    op.create_index(op.f('ix_leads_source_platform'), 'leads', ['source_platform'], unique=False)
    op.create_index(op.f('ix_leads_source_post_id'), 'leads', ['source_post_id'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_source_post_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_source_platform'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_approval_requests_status'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_post_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_analytics_metrics_timestamp'), table_name='analytics_metrics')
    op.drop_index(op.f('ix_analytics_metrics_post_id'), table_name='analytics_metrics')
    op.drop_index(op.f('ix_analytics_metrics_platform'), table_name='analytics_metrics')
    op.drop_index(op.f('ix_analytics_metrics_metric_type'), table_name='analytics_metrics')
    op.drop_table('analytics_metrics')
    op.drop_index(op.f('ix_social_posts_user_id'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_status'), table_name='social_posts')
    op.drop_table('social_posts')
    # ### end Alembic commands ###
